### ISSUE TITLE
capacitor-lab-basics TODO list

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/capacitor-lab-basics#12]
In 8/6/2015 design meeting, we decided that it would be helpful to create a TODO list for the largest outstanding issues and TODO's for this sim.  The following is the compiled list as of 8/7/15.  New items are likely to be added.

TODO:
- [x] Add a draggable Voltmeter with draggable probes.
- [x] Add a gray shaded sphere to the end of the circuit switch wire.
  - Shaded sphere radius should be smaller than hinge node and larger than hinge pin
- [x] Add a check box in control panels to control current indicator node visibility.
- [x] Current indicators should be visible by default.
- [x] Stacked control panels should have the same width.
- [x] For "Capacitance" screen, remove control panel options that are irrelevant.
- [x] Control panel order should be "Plate Charges", "Current", "Electric Field"
- [x] Battery specular highlight and slider orientation need to be reversed, and slider track should be white.
- [x] Stroke on circuit switch connection points should be dashed colorblind red.
- [x] Change order of magnitude on all graphs to pico.
- [x] Number of plate charges should remain constant on capacitor when capacitor is disconnected from battery and capacitance changes.
- [x] Arrows should align perfectly with field lines
- [x] Light Bulb should immediately turn off when disconnected from capacitor
- [x] Expand bounds on circuit switch wire segment so that it is easier to drag
- [ ] BulbNode should be moved to common code, see https://github.com/phetsims/scenery-phet/issues/170
- [ ] i18n outfitting
- [x] Code refactoring and tidying in preparation for https://github.com/phetsims/capacitor-lab-basics/issues/11
- [x] Performance Checks

**Comment by jessegreenberg** [comment]
> Performance Checks

What is the status of this?  How did this sim perform through dev testing?

**Comment by jessegreenberg** [comment]
Checked with QA team, performance was good on tablets in the dev test.

**Comment by jessegreenberg** [comment]
Closing this issue.  Remaining items have independent issues to track progress.
