### ISSUE TITLE
Items to include in the Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#134]
There are a few issues that have been addressed, but have been left open because they'll require documentation in the Teacher Tips. I've decided to close the original issues and consolidate them here instead.
- [x] #57 - Minimum of 1 E-field line per quadrant
- [x] #59  - Density of E-field lines maps to magnitude
- [x] #60 - Precision issues
- [x] #138 - Battery threshold 
- [x] #150 - Plate charge bar graph displays abs(Q)
- [x] #152 - The current arrows show the direction of the current, but do not reflect the magnitude.
- [x] The electric field lines have been idealized as that of an infinite parallel-plate capacitor. (Fringe fields are beyond the scope of this sim.)
- [x] Light bulb resistance is extremely large (0.5x10^12 Ohms) so that the discharge times would be observable.
- [x] Resistance is not explicitly modeled when charging the capacitor. The capacitor appears to charge instantaneously, which could be explained by very low internal resistance in the battery/wires. This was done so that students would see immediate feedback when charging the capacitor.
- [x] The battery is used to set capacitor voltage, which sometimes has odd side effects. For example, connecting a charged capacitor to a 0V battery will drain the capacitor.
- [x] The entire voltmeter probe is conductive (not just the tip), so it's possible to encounter situations where the voltmeter shows some defined value, despite the tip being located in the air or on the light bulb's glass casing.
- [x] When disconnected, the charge on the capacitor is conserved.
- [x] #143 

![image](https://cloud.githubusercontent.com/assets/8419308/19737758/fb78362e-9b71-11e6-9590-2f89464bbc42.png)

**Comment by arouinfar** [comment]
Marking as on-hold until the sim is closer to publication.

**Comment by arouinfar** [comment]
Model simplifications have been noted in the teacher tips.
