### ISSUE TITLE
TODO list for capacitor-lab-basics accessible content

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/capacitor-lab-basics#21]
@EmilyRandall has been doing great work adding accessible content to Capacitor Lab: Basics.  The DOM has headings, labels, and descriptions with a good structure.  In 'forms' mode, it works well with predictable behavior.  Here is a short TODO list that should get the sim working from the perspective of a document.

 - [ ] Add accessible content to checkboxes/checkbox groups
 - [ ] Find an appropriate aria role for the circuit and its elements so that AT toggles to application mode implicitly
 - [ ] Find appropriate aria role for the voltmeter probes to toggle to application mode
 - [ ] Use an input of type range for the capacitor geometry sliders
 - [ ] Pressing 'enter' on circuit switch toggle buttons seems to move focus to battery
 - [ ] Replace ```innerText``` with ```textContent``` for compatibility with Firefox

Finding aria roles is an experimental solution that we are researching.  This only works well in the leading browsers for accessibility.

**Comment by jessegreenberg** [comment]
I notice that the checkboxes can only be read in forms mode.  This is a separate issue that will take investigation.

**Comment by phet-steele** [comment]
> Pressing 'enter' on circuit switch toggle buttons seems to move focus to battery

@jessegreenberg pressing "enter" on bar graph toggle buttons (second screen) moves focus to the capacitance checkbox

**Comment by jessegreenberg** [comment]
Removing assignment until we continue work on this sim for a11y.
