### ISSUE TITLE
Capacitor Lab Basics Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/capacitor-lab-basics#7]
## Design
- [x] **Sim folder and design doc created** (Date: 06/03/2015) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Sim suggestions doc reviewed**
- [x] **Learning goals and standards identified** (Date: 06/03/2015)
- [x] **Design concept complete**  (Date: 07/09/2015)
- [x] **Wireframes complete** (Date: 07/16/2015) 
- [x] **Mockups complete** (Date: 08/06/2015) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion** 
- [x] **Interviews complete** (Date: 06/24/2016) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 10/18/2017) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] Add an activity
  - [x] Sim primer draft (See https://github.com/phetsims/capacitor-lab-basics/issues/235)
- [x] **Post-publication items** 
  - [x] Add to Edmodo
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [x] Sim primer (create issue, publish ideally within 1 month of live sim)  (See https://github.com/phetsims/capacitor-lab-basics/issues/235)

## Implementation
- [x] **Repository created** (Date: 10/24/2014)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to chipper/data/ files
- [x] **Development started** (Date: 06/04/2015)
- [x] **Sim is "feature complete"** (Date: 10/15/2015)
- [x] **Code review completed** (Date: 10/16/2017) 
- [x] **Pre-publication items** 
  - [x] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Verify credits
- [x] **Published** (Date: 11/14/2017) 
  - [x] README.md updated using `grunt published-README` (in master and release branch)
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
 
## QA
- [x] **Dev testing started** (Date: 10/18/2017) 
- [x] **Dev testing completed** (Date: 11/07/2017) 
- [x] **First RC published** (Date: 11/07/2017)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 11/14/17)

**Comment by ariel-phet** [comment]
## Design
- [ ] **Sim folder and design doc created** (Date: 06/03/2015) 
  - [ ] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [ ] Place design doc in the sim folder
- [ ] **Sim suggestions doc reviewed**
- [ ] **Learning goals and standards identified** (Date: 06/03/2015)
- [ ] **Design concept complete**  (Date: 07/09/2015)
- [ ] **Wireframes complete** (Date: 07/16/2015) 
- [ ] **Mockups complete** (Date: 08/06/2015) 
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [ ] **Interviews complete** (Date: //) 
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
- [ ] **Pre-publication items** 
  - [ ] Auxilary screenshots (up to 3 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Add an activity
  - [ ] Sim primer draft
- [ ] **Post-publication items** 
  - [ ] Add to Edmodo
  - [ ] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [ ] **Repository created** (Date: 10/24/2014)
  - [ ] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [ ] simula-rasa used to create project skeleton
  - [ ] README.md created using `grunt unpublished-readme`
  - [ ] Collaborators added (such as QA team, designers, etc)
  - [ ] standard GitHub label set applied
  - [ ] repository added to chipper/data/ files
- [ ] **Development started** (Date: 06/04/2015)
- [ ] **Sim is "feature complete"** (Date: 10/15/2015)
- [ ] **Code review completed** (Date: 10/16/2017) 
- [ ] **Pre-publication items** 
  - [ ] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [ ] Verify credits
- [ ] **Published** (Date: //) 
  - [ ] README.md updated using `grunt published-README` (in master and release branch)
  - [ ] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
 
## QA
- [ ] **Dev testing started** (Date: //) 
- [ ] **Dev testing completed** (Date: //) 
- [ ] **First RC published** (Date: //)
  - [ ] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [ ] **RC testing completed** (Date: //)

**Comment by ariel-phet** [comment]
@arouinfar this sim is getting close, time to start checking off some items!

**Comment by arouinfar** [comment]
@ariel-phet can we add LoL icons and descriptions to the checklist? Moving forward, all new science sims will be integrated into LoL, so the master checklist seems like an appropriate home for these items.

**Comment by jonathanolson** [comment]
Deployed http://phet.colorado.edu/sims/html/capacitor-lab-basics/1.5.0/capacitor-lab-basics_en.html, should be ready for @arouinfar to prepare for full publication.

**Comment by ariel-phet** [comment]
@arouinfar the rest of the tasks are yours.
